### ISSUE TITLE
Idea: Nicer assertions for collections

### ISSUE THREAD

**Issue by rtfeldman** [project-fuzzball/test#1]
These would be a nice way to give better output for collections, e.g. incorporating diffs, expected length vs actual length, etc.

Some ideas:

``` elm
Assert.equalToList : List a -> List a -> Assertion
```

``` elm
Assert.equalToSet : Set a -> Set a -> Assertion
```

``` elm
Assert.equalToDict : Dict a -> Dict a -> Assertion
```

**Comment by mgold** [comment]
Does `Assert.equalToList` ignore order? If it did, it would bring new functionality over `Assert.equal`, not just new failure output.

**Comment by rtfeldman** [comment]
I don't think it should, no...if order doesn't matter, I'd just sort them both before doing the comparison.
