### ISSUE TITLE
Overall Design

### ISSUE THREAD

**Issue by rtfeldman** [project-fuzzball/test#5]
# Project Fuzzball: Revamping elm-test

This is something I've been working on with @mgold, with design input from @evancz, @eeue56, @scottcorgan, and @avh4.

The goal is for this to replace `elm-test`, but we wanted to get feedback first so we're doing a beta release under the codename Project Fuzzball. Once we're satisfied that it's a worthy successor for `elm-test`, we'll merge these changes into `elm-community/elm-test` and deprecate this package.

This is called "project-fuzzball" and not something like "elm-test-revamp" to avoid confusion on the package repo. This is not battle-tested yet!
## Trying the beta

Get the beta release with `npm install -g project-fuzzball-test` - but BEWARE! The binary it produces is called `elm-test`, so this **will** replace your global `elm-test` installation if you have one!

Documentation:

[Test](http://package.elm-lang.org/packages/project-fuzzball/test/1.0.0/Test) (basic API)
[Node.js runner](http://package.elm-lang.org/packages/project-fuzzball/node/1.0.0/Test-Runner-Node) (use with the `elm-test` binary)
[HTML runner](http://package.elm-lang.org/packages/project-fuzzball/test-runner/1.0.0/Test-Runner-Html) (use with `elm-reactor`)
## Upgrading Gradually

There are a bunch of API changes in here, but upgrading is not an all-or-nothing proposition. [legacy-elm-test](https://github.com/rtfeldman/legacy-elm-test) is a drop-in replacement for today's `elm-test` API (including `elm-check` integration) that is written in terms of the new API. The idea is that you can drop it in and start using the new runners right away, without rewriting your tests.

(You'll still want to upgrade eventually, to get the benefits of the new stuff, but this gives you a more gradual path forward.)
## Screenshots

This is what you get when a test run fails after installing running something like `elm-test ExampleFailingTests.elm`.

Colors are set using [chalk](https://www.npmjs.com/package/chalk), which detects when being run on a CI server and doesn't bother outputting them. Windows users see intentionally-chosen ASCII alternatives to the unicode characters here.

<img width="494" alt="screen shot 2016-06-16 at 4 01 01 pm" src="https://cloud.githubusercontent.com/assets/1094080/16135939/9711ada8-33db-11e6-8dbc-e8caec22fe9b.png">

Here's the HTML runner's output.

You get this by starting `elm-reactor` and opening your test file.

<img alt="screen shot 2016-06-16 at 3 59 30 pm" src="https://cloud.githubusercontent.com/assets/1094080/16135890/5a864b00-33db-11e6-8ab0-9ea60152f785.png">
## First-class fuzz tests

This is the big change. In the new API, here's how you'd write a test that runs once:

``` elm
testRemoveNumbers : Test
testRemoveNumbers =
    describe "the removeNumbers function"
        [ test "returns an empty string when there are no numbers" <|
            \_ ->
                removeNumbers "blah blah"
                    |> Assert.equal ""
        ]
```

Here's how you write a [fuzz test](https://en.wikipedia.org/wiki/Fuzz_testing) that runs several times with randomly-generated inputs:

``` elm
testRemoveNumbers : Test
testRemoveNumbers =
    describe "the removeNumbers function"
        [ fuzz3 string float string "removes a number in the middle of a string" <|
            \prefix num suffix ->
                removeNumbers (prefix ++ toString num ++ suffix)
                    |> Assert.equal (prefix ++ suffix)
        ]
```

That's it.

This will generate a random string, a random float, and a random string, and pass them as arguments to that anonymous function. The function will get run 100 times with different randomly-generated arguments each time. (You can configure the run count if you don't want 100.)

If all of those runs pass, the test as a whole passes. If any fail, `elm-test` will do a "shrinking" process to try and find the minimal set of randomly-generated inputs that reproduce the failure (so you don't see redundant failures). It'll then report all the failures it encountered for this test, followed by the randomly-generated inputs that led to the failure:

```
↓ the removeNumbers function
✗ removes a number in the middle of a string

► Given ("foo", 1.1, "bar")

Expected "foo.bar"
to equal "foobar"

► Given ("foo", -1, "bar")

Expected "foo-bar"
to equal "foobar"
```

This one failed test surfaces two bugs. We wrote a function that removes numbers, but although we're removing digits, we aren't properly detecting and removing decimal points or minus signs.

These "fuzz tests" are now both easier to write (no need to separately integrate `elm-check`; it just works right out the box) and give you nicer output (failures stay grouped under the originating test, and include the exact inputs that caused the failure).
## Non-blocking execution

All tests are now wrapped in functions, so they don't get evaluated right when the module loads. This means test runners can do things like reporting progress, running in parallel, etc.

The status quo is that the runner evaluates all tests as soon as the module loads, thereby blocking the thread until all the tests have completed. It has made features like those impossible, but the new API means we can actually do things like this.
## API Change Overview
- `test` now takes a `(() -> Assertion)` function as its final argument instead of an `Assertion`
- `Assertion` now just wraps either a success or failure (with message), and has no further knowledge of what kind of assertion it is.
- `suite` is now called `describe`
- `Assert` exposes more assertion functions than before
- There are different kinds of runners, which present test run output differently. Check out the [Node runner](http://package.elm-lang.org/packages/project-fuzzball/node/1.0.0/Test-Runner-Node) and the [HTML runner](http://package.elm-lang.org/packages/project-fuzzball/test-runner/1.0.0/Test-Runner-Html)
## Future Plans
- Running tests in parallel, so they use all cores, via [elm-web-workers](https://github.com/rtfeldman/elm-web-workers/) (which works on Node too. Yes, really! Multithreading on one process!) Designing the API for non-blocking execution makes this possible without test authors having to do extra work; the feature can just ship and things get faster.
- Providing ways to get CI-friendly structured output, so CI servers can know more than just "everything passed" or "there were some failures"
- Investigating similarly better support for [testing effects](http://package.elm-lang.org/packages/avh4/elm-testable) and html stuff.

**Comment by mgold** [comment]
`elm-check integration` -> `elm-check` integration

Otherwise looks good.

**Comment by eeue56** [comment]
I think you need more diffs between old elm-test and new elm-test

**Comment by rtfeldman** [comment]
@eeue56 good call; added an "API Change Overview" section...let me know if you think anything's missing!

**Comment by mgold** [comment]
I think you should move that up, above the "upgrading gradually" section. The legacy wrapper should sound like the _alternative_, not the main thing you're pushing. "Yeah, it's gonna be great, here's the new API, yes there are a few changes -- except that you can use this other library..."

**Comment by skybrian** [comment]
I found the screenshot to be a bit confusing since the test failures aren't very realistic. (If you were testing a real oxfordify library, the bugs wouldn't look like this.)

**Comment by mgold** [comment]
Hmm, maybe have a look at [this real-world example](https://github.com/mgold/elm-nonempty-list/commit/5364a78e43fd5758a7b851cf072468e1d1971052)?

Also, are we writing this for the NRI or Elm blogs? If so that bumps the quality requirements a bit, and I'll give it a more stringent look.

I learned in doing that upgrade that the runner story is way too complicated. Maybe I completely breezed through the docs (which I'd like to take a pass over at some point in the next few days), but it wasn't obvious how to get a plain HTML page of results. Well, until I remembered Richard saying something about wanting to not depend on `elm-lang/html`, and I eventually found the other library. That's a valid concern and I'd like to run through that as well.

**Comment by studious** [comment]
My 2 cents worth.
I often find reading validation results confusing when the only explanation is 'expected' and 'to eq'. 

I constantly forget if the expected is the actual or the assertion. Rspec has some great language that clears that up.

**Comment by mgold** [comment]
Originally, the api used `{ expected : a, actually : a }` for exactly that reason. But Richard found that the actual would be built up in a pipeline while the expected was usually a simple expression. So we went with `actual |> Assert.equal expected`.

**Comment by rtfeldman** [comment]
Yep, all very true.

I just had an idea: what if we named the expectations to match the output?

So you write:

``` elm
test "still contains one item" <|
    \() ->
        oxfordify "This sentence contains " "." [ "one item" ]
            |> Expect.toEqual "This sentence contains one item."
```

...and the output uses the same structure and words:     

![screen shot 2016-06-23 at 6 47 38 pm](https://cloud.githubusercontent.com/assets/1094080/16325447/1d3060ae-3973-11e6-8622-7cbf93cf294d.png)

So changes would be:
- Type signatures and current pipeline-friendliness remain intact
- `Assert` is renamed to `Expect` (and `Assertion` becomes `Expectation`)
- `equal` is renamed `toEqual` and so on (the most verbose being `toBeGreaterThan` instead of the current `greaterThan`)
- Output failures use the actual structure and function name, to indicate how failed inputs map to arguments

Thoughts?

**Comment by mgold** [comment]
And `Expect.toBeTrue` and `Expect.toBeFalse` right?

I like the idea - it's a bit more verbose but it reads like rspec which influenced jasmine, so people are likely to be familiar with it.

**Comment by rtfeldman** [comment]
> And `Expect.toBeTrue` and `Expect.toBeFalse` right?

Makes sense to me!

**Comment by studious** [comment]
The implementation syntax wasn't at the heart of my original comment it was trying to work out what the actual vs expected was.

I had imagined something like the following as an idea.

```
2. ↓ oxfordify
   ↓ given a sentence with one item
   ✗ still contains one item

   Expected  "This sentence contains one item."
   toEqual
   Actual    "Alice, Bob, and Claire"
```

**Comment by rtfeldman** [comment]
@studious yep, but the critical thing is being able to map which outputted value corresponds to which argument.

So suppose you have the same `Assert.equal` and just different output:

### Original

``` elm
test "still contains one item" <|
    \() ->
        oxfordify foo
            |> Assert.equal bar
```

```
2. ↓ oxfordify
   ↓ given a sentence with one item
   ✗ still contains one item

   Expected  "This sentence contains one item."
   toEqual
   Actual    "Alice, Bob, and Claire"
```

We now have the words "expected" and "actual" in the output, but which one corresponds to `foo` and which one corresponds to `bar`? That's what I need to know in order to know which value was wrong. 😄 

With this version, I think it's a lot easier to tell:

### Expect-style

``` elm
test "still contains one item" <|
    \() ->
        oxfordify foo
            |> Expect.toEqual bar
```

```
2. ↓ oxfordify
   ↓ given a sentence with one item
   ✗ still contains one item

   Expected  "This sentence contains one item."

   toEqual   "Alice, Bob, and Claire"
```

I think it's easier to figure out which one corresponds to `foo` and which corresponds to `bar`, yeah?

**Comment by skybrian** [comment]
Go tests sometimes use "got" and "want". (Just as another possibility.)

https://talks.golang.org/2014/testing.slide#4

**Comment by rtfeldman** [comment]
Made a PR to see how everything would shake out with `Expect` style: https://github.com/project-fuzzball/test/pull/10

**Comment by studious** [comment]
@skybrian yeah.

I often read the result in English as
`I Expected "that my input -> output (actual)" is toEqual "my desired output"`

When it is
`I Expected "my desired output" toEqual "this input -> output"`

This is the confusion that I was wanting to clear up. Just the reading of the result

**Comment by genthaler** [comment]
May I ask, why are you including fuzz testing capability in the library, rather than separating it similarly to elm-check? And how does this implementation of fuzz testing differ from elm-check's?

**Comment by rtfeldman** [comment]
Integration gets you:
- When a test fails, being able to tell you what the inputs were that caused the failure, while still having the comparison libraries decoupled
- Being able to distribute seeds across all tests ahead of time makes deterministic parallelization possible without extra effort from the test author
- Less friction to write a style of test that's broadly useful and doesn't seem like it should be something you need to go out of your way to access

**Comment by genthaler** [comment]
Fair enough. 
I notice you haven't used elm-check's DBC style DSL.
Do you see fuzzball replacing elm-check?

**Comment by rtfeldman** [comment]
That's the idea, yeah - unify elm-check and elm-test, and provide a really low-friction, consistent API for both use cases!

**Comment by widged** [comment]
I personally much prefer `Assert.equal` to `Expect.toEqual`, as I find the former much quicker to read and less ambiguous. When it comes to shortcuts like 'toBeGreaterThan', I would prefer to have them in another lib (CheckExtras). The javascript world has more than 10 variants of such syntax. Trying to include this type of options brings the risk of making it too open to change. For a base library, I would presume that best would be to aim for open for extension, but closed for modification.

**Comment by knewter** [comment]
I like the new proposed syntax, and I'm actually for having a broad set of extended matchers built in as a knee jerk, but at the same time I see the wisdom in what @widged suggests. Think about documenting what people extending the matchers looks like. I'll have a look at the source to make sure it's clear to me.

**Comment by knewter** [comment]
Had a look. So trivial, very nice. I don't know. I like the idea of not having to bring in extra stuff for extended matchers. For instance if ex_unit didn't have assert in Delta, and i had to go to another package for it, I would be sad

**Comment by rtfeldman** [comment]
> I personally much prefer `Assert.equal` to `Expect.toEqual`, as I find the former much quicker to read and less ambiguous.

I'm definitely sympathetic to this. Obviously people can extend it however they like, but my goal is for the base to be as nice as possible. My philosophy regarding extended matchers is "you _can_ reach for them, but if I do a good enough job you won't feel the need to."

This discussion is crystallizing some design goals:
- Pipeline-Friendly
- Concise
- Easy to tell which argument corresponds to which output value

I think with a slight formatting change to make use of Unicode box drawing characters, `Expect.equal` can be as clear as `Expect.equalTo`, and hit all these goals:

``` elm
test "still contains one item" <|
    \() ->
        oxfordify foo
            |> Expect.equal bar
```

```
2. ↓ oxfordify
   ↓ given a sentence with one item
   ✗ still contains one item

       "This sentence contains one item."
       ╷
       │ Expect.equal
       ╵
       "Alice, Bob, and Claire"
```

(With the no-colors log runner, since updating the colorful one is more work.)

![screen shot](https://cloud.githubusercontent.com/assets/1094080/16352083/aa5bb4ae-3a1f-11e6-81b7-a63c03af52ca.png)

![screen shot](https://cloud.githubusercontent.com/assets/1094080/16352054/7dcc4eee-3a1f-11e6-9b03-63a9bda560fa.png)

Thoughts @widged @knewter @studious?

**Comment by rtfeldman** [comment]
I have a workshop tomorrow where 75 people will get to make first-impressions of this, so since this is an experimental repo, I'm gonna go ahead and publish the current iteration as 2.0.0 and see what feedback we get!

**Comment by knewter** [comment]
That's really neat.  I wouldn't have thought of signifying it with the pipe
like that, but I think it's totally clear that way!

**Comment by mgold** [comment]
My gut reaction to the pipe is "I don't like it" -- and maybe there's an actual argument to be made based on familiarity with rspec -- but let's do the science and see how a crowd of people react.

**Comment by rtfeldman** [comment]
Incidentally, the output format was positively received at the workshop!

**Comment by mgold** [comment]
What does it look like for `Expect.toBeTrue` and false?

**Comment by rtfeldman** [comment]
Same as always - just prints the failure String the user entered!

**Comment by rtfeldman** [comment]
It's alive! 🎉
