### ISSUE TITLE
Handling Debug.crash

### ISSUE THREAD

**Issue by rtfeldman** [project-fuzzball/test#6]
If someone calls `Debug.crash`, we should fail the test with a nice error message, and continue running the remaining tests as normal.

**Comment by mgold** [comment]
That would be pretty cool, but I'm not sure it's possible (without Native code).

**Comment by rtfeldman** [comment]
Yeah I think the Node runner can do it.

**Comment by mgold** [comment]
Oh, because the exception can be caught in the isolated process. Right on!
