### ISSUE TITLE
Watch Mode

### ISSUE THREAD

**Issue by rtfeldman** [project-fuzzball/test#7]
Jacob on Slack had a cool idea, and I'm just gonna screencap it here:

![screen shot 2016-06-17 at 1 41 47 pm](https://cloud.githubusercontent.com/assets/1094080/16164025/48a30d5e-3491-11e6-99b2-0acbb6dd7549.png)

**Comment by mgold** [comment]
So, basically a "rerun failed tests" button? Except wouldn't that have to recompile the tests and (without hot-swapping working) mean destroying the state about what failed? Might work better server-side...

**Comment by rtfeldman** [comment]
Yeah I imagine it'd just keep running, watching for changes, and rerun as
appropriate when things changed. Definitely seems doable!
